[package]
name = "monitor-trade"
version.workspace = true
edition.workspace = true

[dependencies]
whirlpool-stream-websocket-client = { workspace = true }

# Utils
clap = { workspace = true }

# Async
tokio = { workspace = true }
